# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('paddress', models.CharField(max_length=40)),
                ('pstatus', models.BooleanField(default=False)),
                ('pvlan', models.CharField(max_length=20)),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20)),
                ('rdate', models.DateTimeField()),
                ('rposition', models.IntegerField()),
                ('rnumberport', models.IntegerField()),
                ('IsDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='prouter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Router'),
        ),
    ]
